### ISSUE TITLE
Broken links in resource documentation

### ISSUE THREAD

**Issue by mjmerin** [Microsoft/macos-cookbook#129]
Apple has changed and/or deprecated links the `macos-cookbook` is using. 

In [certificates](https://github.com/Microsoft/macos-cookbook/blob/master/documentation/resource_certificate.md), the `learn more about security` link is broken.

In [keychain](https://github.com/Microsoft/macos-cookbook/blob/master/documentation/resource_keychain.md), the `learn more about security` link is broken.

In [plist](https://github.com/Microsoft/macos-cookbook/blob/master/documentation/resource_plist.md), the links for `defaults`, `plutil`, and `PlistBuddy` are all broken.

In [spotlight](https://github.com/Microsoft/macos-cookbook/blob/master/documentation/resource_spotlight.md), the `learn more about spotlight` link is broken.

**Comment by americanhanko** [comment]
As far as I can tell, Apple removed the online man pages.
