### ISSUE TITLE
macos 10.14 and later only allows control if Screen Sharing is enabled through System Preferences

### ISSUE THREAD

**Issue by americanhanko** [Microsoft/macos-cookbook#131]
Usage of the`ard` resource in macOS Mojave results in the following message from macOS:

```
Warning: macOS 10.14 and later only allows control if Screen Sharing is enabled through System Preferences.
```

Additionally, there have been several reports that, when connecting to a VM or metal over VNC, **observing** works but **controlling**  does not.

**Comment by jazaval** [comment]
Resolved by #147
