### ISSUE TITLE
Option to remove Feedback Assistant from beta images

### ISSUE THREAD

**Issue by americanhanko** [microsoft/macos-cookbook#132]
There have been a few reports that the Feedback Assistant app is occasionally intrusive and causes problems with certain types of software tests that use AppleScript/GUI. I propose we add an attribute to remove the application altogether (or disable the server that launches the app). SIP does need to be disabled in order to remove the app, and I'm pretty sure this daemon is installed via software updates and/or enrolling in the developer seed with the macos beta package. 

```ruby
default['macos']['disable_feedback_assistant'] = boolean
```

**Comment by jazaval** [comment]
We didn't see this issue with any of the Catalina betas - it seems Apple stopped having Feedback Assistant popup (although the application was still present in the betas). Will reconsider if the behavior returns in future betas.
