### ISSUE TITLE
Feature Request: resource for profiles

### ISSUE THREAD

**Issue by kmf** [Microsoft/macos-cookbook#141]
I would love the ability to import profiles that where generated from either "Apple Configurator 2" or "Profile Manager"

via a cookbook with `files/wifi_network.mobileconfig`

```
directory '/tmp' do
    action :create
end

cookbook_file '/tmp/wifi_network.mobileconfig' do
    source 'wifi_network.mobileconfig'
    action :create
end

execute 'import_wifi' do
  command '/usr/bin/profiles -I -F /tmp/wifi_network.mobileconfig'
  action :run
end
```

**Comment by jazaval** [comment]
@kmf Have you looked into using `osx_profile`: https://docs.chef.io/resource_osx_profile.html? Please let us know if there's a specific feature or use-case that this Chef core resource doesn't work for, and we'll consider submitting it to Chef core.

**Comment by tas50** [comment]
Do feel free to let us know if that’s missing anything. We’re eager to improve Mac support for Chef

**Comment by kmf** [comment]
@jazaval exactly what I was looking for!
