### ISSUE TITLE
xcode resource :install_gem action on Mojave marks all CLI tools for update

### ISSUE THREAD

**Issue by mattlqx** [Microsoft/macos-cookbook#142]
Using the `:install_gem` action on Mojave (10.14) marks all available CLI tools updates for update in Software Update. 

Using latest 2.5.0 cookbook:

```
xcode '10.0' do
  action :install_gem
end
```

Leads to:

![screen shot 2018-09-28 at 8 26 13 am](https://user-images.githubusercontent.com/739851/46217931-33b55580-c2f8-11e8-9836-3c5dd240c0b4.png)

**Comment by jazaval** [comment]
Thanks for catching this! This is likely due to the `CommandLineTools` class not deleting the sentinel file, something that happened in the 2.5.0 refactor. I will update it to do so in our Mojave release, which we are wrapping up.

**Comment by jazaval** [comment]
Resolved by #147
