### ISSUE TITLE
XCVersion is hard coded

### ISSUE THREAD

**Issue by damacus** [Microsoft/macos-cookbook#168]
The helper for xcversion fails if Chef is installed in another place, this is common if you're running using chefdk/chef-workstation. 

https://github.com/Microsoft/macos-cookbook/blob/74177c45c368c36bb4a2b44db1ace025baea5945/libraries/xcversion.rb#L7

**Comment by jazaval** [comment]
Thanks for opening this, @damacus. We should be able to get a fix out in the next day or so.
