### ISSUE TITLE
[BUG] Latest version in the supermarket is 3.4.2

### ISSUE THREAD

**Issue by damacus** [microsoft/macos-cookbook#243]
## Describe the Bug 

The latest version of this cookbook in GitHub is 4.2.2, but supermarket.chef.io has 3.4.2 as the latest version

There also no tags or branches that people could pin to.

**Comment by jazaval** [comment]
Hey @damacus - thanks for catching this. Our release job has only been working to our internal supermarket!

**Comment by damacus** [comment]
Ah hah! 

Any chance you can also push up the tags so we know what's on the supermarket?
