### ISSUE TITLE
macos_user should allow adding to group(s)

### ISSUE THREAD

**Issue by mjmerin** [Microsoft/macos-cookbook#40]
The macos_user resource should have a property that specifies what group(s) the macos_user belongs to. 

Currently adding a user to a group requires the usage of the macos_user resource, followed by the Chef core group resource. 

```
macos_user 'create admin user ' do
  username 'johnd'
  fullname 'John Doe'
  password 'password'
  admin true
  action :create
end

group 'groups for some action ' do
  group_name 'csi'
  members 'johnd'
  action :create
end

**Comment by americanhanko** [comment]
Addressed with changes introduced in #43
