### ISSUE TITLE
Spotlight resource does not verify metadata server is running 

### ISSUE THREAD

**Issue by jazaval** [Microsoft/macos-cookbook#45]
Spotlight resource assumes that the metadata server is running and hasn't been disabled with `launchctl unload`.

This requires a workaround of adding a `launchd` resource to start it and a small delay block to allow for it to finish spinning up before the `spotlight` resource is called:

```
launchd 'metadata server' do 
  path '/System/Library/LaunchDaemons/com.apple.metadata.mds.plist' 
  action :enable 
end 
 
ruby_block 'wait for metadata server spin-up' do 
  block { sleep 2 } 
end

spotlight '/' 
```

**Comment by mjmerin** [comment]
Resolved in Release 2.4
