### ISSUE TITLE
plist resource does not support ownership or mode

### ISSUE THREAD

**Issue by americanhanko** [Microsoft/macos-cookbook#51]
New plists can now be created with the `plist` resource, but if a user plist is created, the permissions need to be modified using the builtin `file` resource. The `plist` resource should have `owner` and `mode` properties. Usage would look like so:

```ruby
plist 'show hidden files' do
  path '/Users/vagrant/Library/Preferences/com.apple.finder.plist'
  entry 'AppleShowAllFiles'
  value true
  owner 'vagrant'
  mode 0o700
end
```

**Comment by v-anshie** [comment]
This was added in Release/2.9
