### ISSUE TITLE
Xcode resource / default recipe attempts to install iOS 10 simulators

### ISSUE THREAD

**Issue by americanhanko** [Microsoft/macos-cookbook#6]
It appears that the iOS 10 simulators are no longer available from Apple, but the Xcode recipe is trying to install them anyway:

```
   * xcode[9] action install_simulators[2017-10-21T12:06:17-07:00] INFO: Processing xcode[9] action install_simulators (macos::xcode line 1) 2017-10-21T19:11:04.7928550Z
parallels-pvm: [2017-10-21T12:06:22-07:00] FATAL: iOS 10 Simulator no longer available from Apple! 2017-10-21T19:11:04.7945450Z
parallels-pvm: [2017-10-21T12:06:22-07:00] INFO: Running queued delayed notifications before re-raising exception
```

This occurred both when the `xcode.rb` recipe was used:

```ruby
include recipe 'macos::xcode'
```

and when the `xcode` resource was alone:

```ruby
xcode '9'
```

More investigation should be done to see why the Xcode resource is attempting to install simulators by default.

**Comment by jazaval** [comment]
I've update the default attributes to use the correct Xcode version - sorry I missed that in PR #3!

**Comment by jazaval** [comment]
#10
