### ISSUE TITLE
Add support for apple_id credentials via chef-vault

### ISSUE THREAD

**Issue by StefanRehder** [Microsoft/macos-cookbook#76]
It would be nice if the values of XCODE_INSTALL_USER and XCODE_INSTALL_PASSWORD could be set via attributes. For example I would like to use chef-vault instead of data bags but the xcode resource currently requires a data bag.

I would like to be able to do something like this in my recipe:

```
include_recipe ‘chef-vault’

vault = chef_vault_item(:credentials, ‘apple_id’)
node.set['macos'][‘apple_id’][‘user’] = vault[‘user’]
node.set['macos'][‘apple_id’][‘password’] = vault[‘password’]

include_recipe 'macos::xcode'
```

It is fine if you default them to the data bag values but it would be nice with an option to override the default values if you want to use chef-vault for example.

**Comment by americanhanko** [comment]
Thanks for this feature request, @StefanRehder - we will certainly look into making this happen.

**Comment by americanhanko** [comment]
Added in #82
