### ISSUE TITLE
Support for hidden user accounts and home folders in macos_user resource

### ISSUE THREAD

**Issue by americanhanko** [Microsoft/macos-cookbook#96]
Apple outlines the steps to do this using the `dscl` command in the [**Hide a user account in macOS**](https://support.apple.com/en-us/HT203998) support article.

**Comment by chrismarlin** [comment]
Implementation details for Directory Services https://support.apple.com/en-us/HT203998

**Comment by americanhanko** [comment]
This got merged in version 2.3 #121 and fixed with #118
